export const FORGOT_PASSWORD_REQUESTED = 'FORGOT_PASSWORD_REQUESTED';
export const FORGOT_PASSWORD_SUCCEEDED = 'FORGOT_PASSWORD_SUCCEEDED';

export const FORGOT_PASSWORD_FAILEDED = 'FORGOT_PASSWORD_FAILEDED';
