export const CREATE_ADMIN_USER_REQUESTED = 'CREATE_ADMIN_USER_REQUESTED';
export const CREATE_ADMIN_USER_SUCCESSED = 'CREATE_ADMIN_USER_SUCCESSED';
export const RENDER_CREATE_FORM_ADMIN_USER_REQUESTED = 'RENDER_CREATE_FORM_ADMIN_USER_REQUESTED';
export const UPDATE_ADMIN_USER_INPUT_OPTION = 'UPDATE_ADMIN_USER_INPUT_OPTION';

