export const RENDER_ADMIN_EDIT_USER_FORM_REQUESTED = 'RENDER_ADMIN_EDIT_USER_FORM_REQUESTED';
export const FILL_ADMIN_USER_DETAIL_FORM = 'FILL_ADMIN_USER_DETAIL_FORM';
export const GET_ADMIN_USER_DETAIL_REQUESTED = 'GET_ADMIN_USER_DETAIL_REQUESTED';
export const GET_ADMIN_USER_DETAIL_SUCCESSED = 'GET_ADMIN_USER_DETAIL_SUCCESSED';
export const ADMIN_EDIT_USER_REQUESTED = 'ADMIN_EDIT_USER_REQUESTED';
export const EDIT_ADMIN_USER_SUCCEEDED = 'EDIT_ADMIN_USER_SUCCEEDED';
export const DELETE_ADMIN_USER_REQUESTED = 'DELETE_ADMIN_USER_REQUESTED';
export const DELETE_ADMIN_USER_SUCCESSED = 'DELETE_ADMIN_USER_SUCCESSED';

export const removeUserRequested = payload => Object.assign({}, { type: DELETE_ADMIN_USER_REQUESTED, data: payload });
